// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicStore.Infrastructure;

#nullable disable

namespace MusicStore.Infrastructure.Migrations
{
    [DbContext(typeof(MusicStoreContext))]
    partial class MusicStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MusicStore.Domain.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSold")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Progressive Rock",
                            Name = "Dark Side of the Moon",
                            Rating = 4.9000000000000004,
                            ReleaseDate = new DateTime(1973, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 45000000
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Pop",
                            Name = "Thriller",
                            Rating = 4.7999999999999998,
                            ReleaseDate = new DateTime(1982, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 66000000
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Rock",
                            Name = "Abbey Road",
                            Rating = 4.7999999999999998,
                            ReleaseDate = new DateTime(1969, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 31000000
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Hard Rock",
                            Name = "Back in Black",
                            Rating = 4.7000000000000002,
                            ReleaseDate = new DateTime(1980, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 50000000
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Rock",
                            Name = "Hotel California",
                            Rating = 4.7000000000000002,
                            ReleaseDate = new DateTime(1976, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 42000000
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Progressive Rock",
                            Name = "The Wall",
                            Rating = 4.9000000000000004,
                            ReleaseDate = new DateTime(1979, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 30000000
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Hard Rock",
                            Name = "Led Zeppelin IV",
                            Rating = 4.7999999999999998,
                            ReleaseDate = new DateTime(1971, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 37000000
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Rock",
                            Name = "Rumours",
                            Rating = 4.9000000000000004,
                            ReleaseDate = new DateTime(1977, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 40000000
                        },
                        new
                        {
                            Id = 9,
                            Genre = "Rock",
                            Name = "Sgt. Pepper's Lonely Hearts Club Band",
                            Rating = 4.7000000000000002,
                            ReleaseDate = new DateTime(1967, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 32000000
                        },
                        new
                        {
                            Id = 10,
                            Genre = "Rock",
                            Name = "Born in the U.S.A.",
                            Rating = 4.5999999999999996,
                            ReleaseDate = new DateTime(1984, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 30000000
                        },
                        new
                        {
                            Id = 11,
                            Genre = "Rock",
                            Name = "The Joshua Tree",
                            Rating = 4.7999999999999998,
                            ReleaseDate = new DateTime(1987, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 25000000
                        },
                        new
                        {
                            Id = 12,
                            Genre = "Pop",
                            Name = "Bad",
                            Rating = 4.7000000000000002,
                            ReleaseDate = new DateTime(1987, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 35000000
                        },
                        new
                        {
                            Id = 13,
                            Genre = "Pop",
                            Name = "Purple Rain",
                            Rating = 4.7999999999999998,
                            ReleaseDate = new DateTime(1984, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 25000000
                        },
                        new
                        {
                            Id = 14,
                            Genre = "Hard Rock",
                            Name = "Appetite for Destruction",
                            Rating = 4.7000000000000002,
                            ReleaseDate = new DateTime(1987, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 30000000
                        },
                        new
                        {
                            Id = 15,
                            Genre = "Pop",
                            Name = "Like a Virgin",
                            Rating = 4.5,
                            ReleaseDate = new DateTime(1984, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 21000000
                        },
                        new
                        {
                            Id = 16,
                            Genre = "Grunge",
                            Name = "Nevermind",
                            Rating = 4.9000000000000004,
                            ReleaseDate = new DateTime(1991, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 30000000
                        },
                        new
                        {
                            Id = 17,
                            Genre = "Rock",
                            Name = "Bat Out of Hell",
                            Rating = 4.7999999999999998,
                            ReleaseDate = new DateTime(1977, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 43000000
                        },
                        new
                        {
                            Id = 18,
                            Genre = "Rock",
                            Name = "A Night at the Opera",
                            Rating = 4.9000000000000004,
                            ReleaseDate = new DateTime(1975, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 15000000
                        },
                        new
                        {
                            Id = 19,
                            Genre = "Pop",
                            Name = "21",
                            Rating = 4.7000000000000002,
                            ReleaseDate = new DateTime(2011, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 31000000
                        },
                        new
                        {
                            Id = 20,
                            Genre = "Rock",
                            Name = "Goodbye Yellow Brick Road",
                            Rating = 4.7999999999999998,
                            ReleaseDate = new DateTime(1973, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 30000000
                        },
                        new
                        {
                            Id = 21,
                            Genre = "Pop",
                            Name = "Whitney Houston",
                            Rating = 4.5999999999999996,
                            ReleaseDate = new DateTime(1985, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 22000000
                        },
                        new
                        {
                            Id = 22,
                            Genre = "Rock",
                            Name = "Brothers in Arms",
                            Rating = 4.7000000000000002,
                            ReleaseDate = new DateTime(1985, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 30000000
                        },
                        new
                        {
                            Id = 23,
                            Genre = "Folk Rock",
                            Name = "Bridge Over Troubled Water",
                            Rating = 4.7000000000000002,
                            ReleaseDate = new DateTime(1970, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 25000000
                        },
                        new
                        {
                            Id = 24,
                            Genre = "Rock",
                            Name = "Physical Graffiti",
                            Rating = 4.7999999999999998,
                            ReleaseDate = new DateTime(1975, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 16000000
                        },
                        new
                        {
                            Id = 25,
                            Genre = "Pop",
                            Name = "Graceland",
                            Rating = 4.7000000000000002,
                            ReleaseDate = new DateTime(1986, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSold = 16000000
                        });
                });

            modelBuilder.Entity("MusicStore.Domain.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            Country = "UK",
                            FirstName = "David",
                            Gender = "Male",
                            LastName = "Gilmour"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 1,
                            Country = "UK",
                            FirstName = "Roger",
                            Gender = "Male",
                            LastName = "Waters"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 2,
                            Country = "USA",
                            FirstName = "Michael",
                            Gender = "Male",
                            LastName = "Jackson"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 2,
                            Country = "USA",
                            FirstName = "Quincy",
                            Gender = "Male",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 3,
                            Country = "UK",
                            FirstName = "Paul",
                            Gender = "Male",
                            LastName = "McCartney"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 3,
                            Country = "UK",
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Lennon"
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 3,
                            Country = "UK",
                            FirstName = "George",
                            Gender = "Male",
                            LastName = "Harrison"
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 3,
                            Country = "UK",
                            FirstName = "Ringo",
                            Gender = "Male",
                            LastName = "Starr"
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 4,
                            Country = "Australia",
                            FirstName = "Angus",
                            Gender = "Male",
                            LastName = "Young"
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 4,
                            Country = "UK",
                            FirstName = "Brian",
                            Gender = "Male",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 11,
                            AlbumId = 5,
                            Country = "USA",
                            FirstName = "Don",
                            Gender = "Male",
                            LastName = "Henley"
                        },
                        new
                        {
                            Id = 12,
                            AlbumId = 5,
                            Country = "USA",
                            FirstName = "Glenn",
                            Gender = "Male",
                            LastName = "Frey"
                        },
                        new
                        {
                            Id = 13,
                            AlbumId = 5,
                            Country = "USA",
                            FirstName = "Joe",
                            Gender = "Male",
                            LastName = "Walsh"
                        },
                        new
                        {
                            Id = 14,
                            AlbumId = 6,
                            Country = "UK",
                            FirstName = "Roger",
                            Gender = "Male",
                            LastName = "Waters"
                        },
                        new
                        {
                            Id = 15,
                            AlbumId = 6,
                            Country = "UK",
                            FirstName = "David",
                            Gender = "Male",
                            LastName = "Gilmour"
                        },
                        new
                        {
                            Id = 16,
                            AlbumId = 7,
                            Country = "UK",
                            FirstName = "Jimmy",
                            Gender = "Male",
                            LastName = "Page"
                        },
                        new
                        {
                            Id = 17,
                            AlbumId = 7,
                            Country = "UK",
                            FirstName = "Robert",
                            Gender = "Male",
                            LastName = "Plant"
                        },
                        new
                        {
                            Id = 18,
                            AlbumId = 7,
                            Country = "UK",
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Paul Jones"
                        },
                        new
                        {
                            Id = 19,
                            AlbumId = 8,
                            Country = "USA",
                            FirstName = "Stevie",
                            Gender = "Female",
                            LastName = "Nicks"
                        },
                        new
                        {
                            Id = 20,
                            AlbumId = 8,
                            Country = "USA",
                            FirstName = "Lindsey",
                            Gender = "Male",
                            LastName = "Buckingham"
                        },
                        new
                        {
                            Id = 21,
                            AlbumId = 8,
                            Country = "UK",
                            FirstName = "Christine",
                            Gender = "Female",
                            LastName = "McVie"
                        },
                        new
                        {
                            Id = 22,
                            AlbumId = 9,
                            Country = "UK",
                            FirstName = "Paul",
                            Gender = "Male",
                            LastName = "McCartney"
                        },
                        new
                        {
                            Id = 23,
                            AlbumId = 9,
                            Country = "UK",
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Lennon"
                        },
                        new
                        {
                            Id = 24,
                            AlbumId = 9,
                            Country = "UK",
                            FirstName = "George",
                            Gender = "Male",
                            LastName = "Harrison"
                        },
                        new
                        {
                            Id = 25,
                            AlbumId = 10,
                            Country = "USA",
                            FirstName = "Bruce",
                            Gender = "Male",
                            LastName = "Springsteen"
                        },
                        new
                        {
                            Id = 26,
                            AlbumId = 10,
                            Country = "USA",
                            FirstName = "Clarence",
                            Gender = "Male",
                            LastName = "Clemons"
                        },
                        new
                        {
                            Id = 27,
                            AlbumId = 11,
                            Country = "Ireland",
                            FirstName = "Bono",
                            Gender = "Male",
                            LastName = ""
                        },
                        new
                        {
                            Id = 28,
                            AlbumId = 11,
                            Country = "Ireland",
                            FirstName = "The Edge",
                            Gender = "Male",
                            LastName = ""
                        },
                        new
                        {
                            Id = 29,
                            AlbumId = 11,
                            Country = "Ireland",
                            FirstName = "Adam",
                            Gender = "Male",
                            LastName = "Clayton"
                        },
                        new
                        {
                            Id = 30,
                            AlbumId = 11,
                            Country = "Ireland",
                            FirstName = "Larry",
                            Gender = "Male",
                            LastName = "Mullen Jr."
                        },
                        new
                        {
                            Id = 31,
                            AlbumId = 12,
                            Country = "USA",
                            FirstName = "Michael",
                            Gender = "Male",
                            LastName = "Jackson"
                        },
                        new
                        {
                            Id = 32,
                            AlbumId = 13,
                            Country = "USA",
                            FirstName = "Prince",
                            Gender = "Male",
                            LastName = ""
                        },
                        new
                        {
                            Id = 33,
                            AlbumId = 14,
                            Country = "UK",
                            FirstName = "Slash",
                            Gender = "Male",
                            LastName = ""
                        },
                        new
                        {
                            Id = 34,
                            AlbumId = 14,
                            Country = "USA",
                            FirstName = "Axl",
                            Gender = "Male",
                            LastName = "Rose"
                        },
                        new
                        {
                            Id = 35,
                            AlbumId = 15,
                            Country = "USA",
                            FirstName = "Madonna",
                            Gender = "Female",
                            LastName = ""
                        },
                        new
                        {
                            Id = 36,
                            AlbumId = 16,
                            Country = "USA",
                            FirstName = "Kurt",
                            Gender = "Male",
                            LastName = "Cobain"
                        },
                        new
                        {
                            Id = 37,
                            AlbumId = 16,
                            Country = "USA",
                            FirstName = "Krist",
                            Gender = "Male",
                            LastName = "Novoselic"
                        },
                        new
                        {
                            Id = 38,
                            AlbumId = 17,
                            Country = "USA",
                            FirstName = "Meat",
                            Gender = "Male",
                            LastName = "Loaf"
                        },
                        new
                        {
                            Id = 39,
                            AlbumId = 18,
                            Country = "UK",
                            FirstName = "Brian",
                            Gender = "Male",
                            LastName = "May"
                        },
                        new
                        {
                            Id = 40,
                            AlbumId = 18,
                            Country = "UK",
                            FirstName = "Freddie",
                            Gender = "Male",
                            LastName = "Mercury"
                        },
                        new
                        {
                            Id = 41,
                            AlbumId = 19,
                            Country = "UK",
                            FirstName = "Adele",
                            Gender = "Female",
                            LastName = "Adkins"
                        },
                        new
                        {
                            Id = 42,
                            AlbumId = 19,
                            Country = "UK",
                            FirstName = "Paul",
                            Gender = "Male",
                            LastName = "Epworth"
                        },
                        new
                        {
                            Id = 43,
                            AlbumId = 20,
                            Country = "UK",
                            FirstName = "Elton",
                            Gender = "Male",
                            LastName = "John"
                        },
                        new
                        {
                            Id = 44,
                            AlbumId = 20,
                            Country = "UK",
                            FirstName = "Bernie",
                            Gender = "Male",
                            LastName = "Taupin"
                        },
                        new
                        {
                            Id = 45,
                            AlbumId = 21,
                            Country = "USA",
                            FirstName = "Whitney",
                            Gender = "Female",
                            LastName = "Houston"
                        },
                        new
                        {
                            Id = 46,
                            AlbumId = 21,
                            Country = "USA",
                            FirstName = "Narada",
                            Gender = "Male",
                            LastName = "Michael Walden"
                        },
                        new
                        {
                            Id = 47,
                            AlbumId = 22,
                            Country = "UK",
                            FirstName = "Mark",
                            Gender = "Male",
                            LastName = "Knopfler"
                        },
                        new
                        {
                            Id = 48,
                            AlbumId = 22,
                            Country = "UK",
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Illsley"
                        },
                        new
                        {
                            Id = 49,
                            AlbumId = 23,
                            Country = "USA",
                            FirstName = "Simon",
                            Gender = "Male",
                            LastName = "Garfunkel"
                        },
                        new
                        {
                            Id = 50,
                            AlbumId = 23,
                            Country = "USA",
                            FirstName = "Paul",
                            Gender = "Male",
                            LastName = "Simon"
                        },
                        new
                        {
                            Id = 51,
                            AlbumId = 23,
                            Country = "USA",
                            FirstName = "Art",
                            Gender = "Male",
                            LastName = "Garfunkel"
                        },
                        new
                        {
                            Id = 52,
                            AlbumId = 24,
                            Country = "UK",
                            FirstName = "Robert",
                            Gender = "Male",
                            LastName = "Plant"
                        },
                        new
                        {
                            Id = 53,
                            AlbumId = 24,
                            Country = "UK",
                            FirstName = "Jimmy",
                            Gender = "Male",
                            LastName = "Page"
                        },
                        new
                        {
                            Id = 54,
                            AlbumId = 24,
                            Country = "UK",
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Paul Jones"
                        },
                        new
                        {
                            Id = 55,
                            AlbumId = 25,
                            Country = "USA",
                            FirstName = "Simon",
                            Gender = "Male",
                            LastName = "Garfunkel"
                        },
                        new
                        {
                            Id = 56,
                            AlbumId = 25,
                            Country = "USA",
                            FirstName = "Paul",
                            Gender = "Male",
                            LastName = "Simon"
                        },
                        new
                        {
                            Id = 57,
                            AlbumId = 25,
                            Country = "South Africa",
                            FirstName = "Ray",
                            Gender = "Male",
                            LastName = "Phiri"
                        },
                        new
                        {
                            Id = 58,
                            AlbumId = 25,
                            Country = "South Africa",
                            FirstName = "Ladysmith",
                            Gender = "Male",
                            LastName = "Black Mambazo"
                        },
                        new
                        {
                            Id = 59,
                            AlbumId = 25,
                            Country = "USA",
                            FirstName = "Linda",
                            Gender = "Female",
                            LastName = "Ronstadt"
                        },
                        new
                        {
                            Id = 60,
                            AlbumId = 25,
                            Country = "South Africa",
                            FirstName = "Joseph",
                            Gender = "Male",
                            LastName = "Shabalala"
                        });
                });

            modelBuilder.Entity("MusicStore.Domain.Models.Artist", b =>
                {
                    b.HasOne("MusicStore.Domain.Models.Album", "Album")
                        .WithMany("Artists")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("MusicStore.Domain.Models.Album", b =>
                {
                    b.Navigation("Artists");
                });
#pragma warning restore 612, 618
        }
    }
}
