using Microsoft.EntityFrameworkCore;
using MusicStore.Domain.Models;

namespace MusicStore.Infrastructure;

public static class DataSeeder
{
    public static void Seed(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Album>().HasData(
            new Album { Id = 1, Name = "Dark Side of the Moon", Genre = "Progressive Rock", ReleaseDate = new DateTime(1973, 3, 1), TotalSold = 45000000, Rating = 4.9 },
            new Album { Id = 2, Name = "Thriller", Genre = "Pop", ReleaseDate = new DateTime(1982, 11, 30), TotalSold = 66000000, Rating = 4.8 },
            new Album { Id = 3, Name = "Abbey Road", Genre = "Rock", ReleaseDate = new DateTime(1969, 9, 26), TotalSold = 31000000, Rating = 4.8 },
            new Album { Id = 4, Name = "Back in Black", Genre = "Hard Rock", ReleaseDate = new DateTime(1980, 7, 25), TotalSold = 50000000, Rating = 4.7 },
            new Album { Id = 5, Name = "Hotel California", Genre = "Rock", ReleaseDate = new DateTime(1976, 12, 8), TotalSold = 42000000, Rating = 4.7 },
            new Album { Id = 6, Name = "The Wall", Genre = "Progressive Rock", ReleaseDate = new DateTime(1979, 11, 30), TotalSold = 30000000, Rating = 4.9 },
            new Album { Id = 7, Name = "Led Zeppelin IV", Genre = "Hard Rock", ReleaseDate = new DateTime(1971, 11, 8), TotalSold = 37000000, Rating = 4.8 },
            new Album { Id = 8, Name = "Rumours", Genre = "Rock", ReleaseDate = new DateTime(1977, 2, 4), TotalSold = 40000000, Rating = 4.9 },
            new Album { Id = 9, Name = "Sgt. Pepper's Lonely Hearts Club Band", Genre = "Rock", ReleaseDate = new DateTime(1967, 5, 26), TotalSold = 32000000, Rating = 4.7 },
            new Album { Id = 10, Name = "Born in the U.S.A.", Genre = "Rock", ReleaseDate = new DateTime(1984, 6, 4), TotalSold = 30000000, Rating = 4.6 },
            new Album { Id = 11, Name = "The Joshua Tree", Genre = "Rock", ReleaseDate = new DateTime(1987, 3, 9), TotalSold = 25000000, Rating = 4.8 },
            new Album { Id = 12, Name = "Bad", Genre = "Pop", ReleaseDate = new DateTime(1987, 8, 31), TotalSold = 35000000, Rating = 4.7 },
            new Album { Id = 13, Name = "Purple Rain", Genre = "Pop", ReleaseDate = new DateTime(1984, 6, 25), TotalSold = 25000000, Rating = 4.8 },
            new Album { Id = 14, Name = "Appetite for Destruction", Genre = "Hard Rock", ReleaseDate = new DateTime(1987, 7, 21), TotalSold = 30000000, Rating = 4.7 },
            new Album { Id = 15, Name = "Like a Virgin", Genre = "Pop", ReleaseDate = new DateTime(1984, 11, 12), TotalSold = 21000000, Rating = 4.5 },
            new Album { Id = 16, Name = "Nevermind", Genre = "Grunge", ReleaseDate = new DateTime(1991, 9, 24), TotalSold = 30000000, Rating = 4.9 },
            new Album { Id = 17, Name = "Bat Out of Hell", Genre = "Rock", ReleaseDate = new DateTime(1977, 10, 21), TotalSold = 43000000, Rating = 4.8 },
            new Album { Id = 18, Name = "A Night at the Opera", Genre = "Rock", ReleaseDate = new DateTime(1975, 11, 21), TotalSold = 15000000, Rating = 4.9 },
            new Album { Id = 19, Name = "21", Genre = "Pop", ReleaseDate = new DateTime(2011, 1, 24), TotalSold = 31000000, Rating = 4.7 },
            new Album { Id = 20, Name = "Goodbye Yellow Brick Road", Genre = "Rock", ReleaseDate = new DateTime(1973, 10, 5), TotalSold = 30000000, Rating = 4.8 },
            new Album { Id = 21, Name = "Whitney Houston", Genre = "Pop", ReleaseDate = new DateTime(1985, 2, 14), TotalSold = 22000000, Rating = 4.6 },
            new Album { Id = 22, Name = "Brothers in Arms", Genre = "Rock", ReleaseDate = new DateTime(1985, 5, 13), TotalSold = 30000000, Rating = 4.7 },
            new Album { Id = 23, Name = "Bridge Over Troubled Water", Genre = "Folk Rock", ReleaseDate = new DateTime(1970, 1, 26), TotalSold = 25000000, Rating = 4.7 },
            new Album { Id = 24, Name = "Physical Graffiti", Genre = "Rock", ReleaseDate = new DateTime(1975, 2, 24), TotalSold = 16000000, Rating = 4.8 },
            new Album { Id = 25, Name = "Graceland", Genre = "Pop", ReleaseDate = new DateTime(1986, 8, 25), TotalSold = 16000000, Rating = 4.7 }
        );
        
        modelBuilder.Entity<Artist>().HasData(
            new Artist { Id = 1, FirstName = "David", LastName = "Gilmour", Gender = "Male", Country = "UK", AlbumId = 1 },
            new Artist { Id = 2, FirstName = "Roger", LastName = "Waters", Gender = "Male", Country = "UK", AlbumId = 1 },
            new Artist { Id = 3, FirstName = "Michael", LastName = "Jackson", Gender = "Male", Country = "USA", AlbumId = 2 },
            new Artist { Id = 4, FirstName = "Quincy", LastName = "Jones", Gender = "Male", Country = "USA", AlbumId = 2 },
            new Artist { Id = 5, FirstName = "Paul", LastName = "McCartney", Gender = "Male", Country = "UK", AlbumId = 3 },
            new Artist { Id = 6, FirstName = "John", LastName = "Lennon", Gender = "Male", Country = "UK", AlbumId = 3 },
            new Artist { Id = 7, FirstName = "George", LastName = "Harrison", Gender = "Male", Country = "UK", AlbumId = 3 },
            new Artist { Id = 8, FirstName = "Ringo", LastName = "Starr", Gender = "Male", Country = "UK", AlbumId = 3 },
            new Artist { Id = 9, FirstName = "Angus", LastName = "Young", Gender = "Male", Country = "Australia", AlbumId = 4 },
            new Artist { Id = 10, FirstName = "Brian", LastName = "Johnson", Gender = "Male", Country = "UK", AlbumId = 4 },
            new Artist { Id = 11, FirstName = "Don", LastName = "Henley", Gender = "Male", Country = "USA", AlbumId = 5 },
            new Artist { Id = 12, FirstName = "Glenn", LastName = "Frey", Gender = "Male", Country = "USA", AlbumId = 5 },
            new Artist { Id = 13, FirstName = "Joe", LastName = "Walsh", Gender = "Male", Country = "USA", AlbumId = 5 },
            new Artist { Id = 14, FirstName = "Roger", LastName = "Waters", Gender = "Male", Country = "UK", AlbumId = 6 },
            new Artist { Id = 15, FirstName = "David", LastName = "Gilmour", Gender = "Male", Country = "UK", AlbumId = 6 },
            new Artist { Id = 16, FirstName = "Jimmy", LastName = "Page", Gender = "Male", Country = "UK", AlbumId = 7 },
            new Artist { Id = 17, FirstName = "Robert", LastName = "Plant", Gender = "Male", Country = "UK", AlbumId = 7 },
            new Artist { Id = 18, FirstName = "John", LastName = "Paul Jones", Gender = "Male", Country = "UK", AlbumId = 7 },
            new Artist { Id = 19, FirstName = "Stevie", LastName = "Nicks", Gender = "Female", Country = "USA", AlbumId = 8 },
            new Artist { Id = 20, FirstName = "Lindsey", LastName = "Buckingham", Gender = "Male", Country = "USA", AlbumId = 8 },
            new Artist { Id = 21, FirstName = "Christine", LastName = "McVie", Gender = "Female", Country = "UK", AlbumId = 8 },
            new Artist { Id = 22, FirstName = "Paul", LastName = "McCartney", Gender = "Male", Country = "UK", AlbumId = 9 },
            new Artist { Id = 23, FirstName = "John", LastName = "Lennon", Gender = "Male", Country = "UK", AlbumId = 9 },
            new Artist { Id = 24, FirstName = "George", LastName = "Harrison", Gender = "Male", Country = "UK", AlbumId = 9 },
            new Artist { Id = 25, FirstName = "Bruce", LastName = "Springsteen", Gender = "Male", Country = "USA", AlbumId = 10 },
            new Artist { Id = 26, FirstName = "Clarence", LastName = "Clemons", Gender = "Male", Country = "USA", AlbumId = 10 },
            new Artist { Id = 27, FirstName = "Bono", LastName = "", Gender = "Male", Country = "Ireland", AlbumId = 11 },
            new Artist { Id = 28, FirstName = "The Edge", LastName = "", Gender = "Male", Country = "Ireland", AlbumId = 11 },
            new Artist { Id = 29, FirstName = "Adam", LastName = "Clayton", Gender = "Male", Country = "Ireland", AlbumId = 11 },
            new Artist { Id = 30, FirstName = "Larry", LastName = "Mullen Jr.", Gender = "Male", Country = "Ireland", AlbumId = 11 },
            new Artist { Id = 31, FirstName = "Michael", LastName = "Jackson", Gender = "Male", Country = "USA", AlbumId = 12 },
            new Artist { Id = 32, FirstName = "Prince", LastName = "", Gender = "Male", Country = "USA", AlbumId = 13 },
            new Artist { Id = 33, FirstName = "Slash", LastName = "", Gender = "Male", Country = "UK", AlbumId = 14 },
            new Artist { Id = 34, FirstName = "Axl", LastName = "Rose", Gender = "Male", Country = "USA", AlbumId = 14 },
            new Artist { Id = 35, FirstName = "Madonna", LastName = "", Gender = "Female", Country = "USA", AlbumId = 15 },
            new Artist { Id = 36, FirstName = "Kurt", LastName = "Cobain", Gender = "Male", Country = "USA", AlbumId = 16 },
            new Artist { Id = 37, FirstName = "Krist", LastName = "Novoselic", Gender = "Male", Country = "USA", AlbumId = 16 },
            new Artist { Id = 38, FirstName = "Meat", LastName = "Loaf", Gender = "Male", Country = "USA", AlbumId = 17 },
            new Artist { Id = 39, FirstName = "Brian", LastName = "May", Gender = "Male", Country = "UK", AlbumId = 18 },
            new Artist { Id = 40, FirstName = "Freddie", LastName = "Mercury", Gender = "Male", Country = "UK", AlbumId = 18 },
            new Artist { Id = 41, FirstName = "Adele", LastName = "Adkins", Gender = "Female", Country = "UK", AlbumId = 19 },
            new Artist { Id = 42, FirstName = "Paul", LastName = "Epworth", Gender = "Male", Country = "UK", AlbumId = 19 },
            new Artist { Id = 43, FirstName = "Elton", LastName = "John", Gender = "Male", Country = "UK", AlbumId = 20 },
            new Artist { Id = 44, FirstName = "Bernie", LastName = "Taupin", Gender = "Male", Country = "UK", AlbumId = 20 },
            new Artist { Id = 45, FirstName = "Whitney", LastName = "Houston", Gender = "Female", Country = "USA", AlbumId = 21 },
            new Artist { Id = 46, FirstName = "Narada", LastName = "Michael Walden", Gender = "Male", Country = "USA", AlbumId = 21 },
            new Artist { Id = 47, FirstName = "Mark", LastName = "Knopfler", Gender = "Male", Country = "UK", AlbumId = 22 },
            new Artist { Id = 48, FirstName = "John", LastName = "Illsley", Gender = "Male", Country = "UK", AlbumId = 22 },
            new Artist { Id = 49, FirstName = "Simon", LastName = "Garfunkel", Gender = "Male", Country = "USA", AlbumId = 23 },
            new Artist { Id = 50, FirstName = "Paul", LastName = "Simon", Gender = "Male", Country = "USA", AlbumId = 23 },
            new Artist { Id = 51, FirstName = "Art", LastName = "Garfunkel", Gender = "Male", Country = "USA", AlbumId = 23 },
            new Artist { Id = 52, FirstName = "Robert", LastName = "Plant", Gender = "Male", Country = "UK", AlbumId = 24 },
            new Artist { Id = 53, FirstName = "Jimmy", LastName = "Page", Gender = "Male", Country = "UK", AlbumId = 24 },
            new Artist { Id = 54, FirstName = "John", LastName = "Paul Jones", Gender = "Male", Country = "UK", AlbumId = 24 },
            new Artist { Id = 55, FirstName = "Simon", LastName = "Garfunkel", Gender = "Male", Country = "USA", AlbumId = 25 },
            new Artist { Id = 56, FirstName = "Paul", LastName = "Simon", Gender = "Male", Country = "USA", AlbumId = 25 },
            new Artist { Id = 57, FirstName = "Ray", LastName = "Phiri", Gender = "Male", Country = "South Africa", AlbumId = 25 },
            new Artist { Id = 58, FirstName = "Ladysmith", LastName = "Black Mambazo", Gender = "Male", Country = "South Africa", AlbumId = 25 },
            new Artist { Id = 59, FirstName = "Linda", LastName = "Ronstadt", Gender = "Female", Country = "USA", AlbumId = 25 },
            new Artist { Id = 60, FirstName = "Joseph", LastName = "Shabalala", Gender = "Male", Country = "South Africa", AlbumId = 25 }
        );
    }
}